import '@/app/globals.css'
import type { Metadata } from 'next'
import { Raleway, Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { NextAuthProvider } from './components/wrapper/provider'

const raleway = Raleway({ 
  subsets: ['latin'],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway"
})
const inter = Inter({ 
    subsets: ['latin'], 
    weight: ["200", "300", "400", "500", "600", "700"],
    variable: "--font-inter"
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${inter.variable}`}>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
